### PR TITLE
Beautify web pages

### PR DESCRIPTION
**Pull request by breezewish**
- Beautify the website
- Move scripts into `website/`
- Run [prettier](https://prettier.io/) for everything

To generate the site:

```
yarn build:script
yarn build:site
```

Since now Viz is redirected directly, maybe we need to modify the Viz page to introduce that "Open snapshot" runs locally in the browser and does not upload anything to PingCAP server.

Note: this PR derives from https://github.com/kennytm/grafana-export/pull/17

### CODE REVIEW

**Comment by kennytm** [comment]
So TBH i don't like including nodejs into the development process very much. After this PR you can't simply open the `index.html` from local file, you've need to do `yarn dev` :shrug:

And if we do introduce nodejs we'd better use a real i18n framework than my ad-hoc css-based one 

Also, the "import" step include steps for both `curl` and `wget` because i know there are system containing one but not the other.

**Comment by breezewish** [comment]
> So TBH i don't like including nodejs into the development process very much. After this PR you can't simply open the index.html from local file, you've need to do yarn dev 🤷

I guess the use case that people don't want to open the website but want to open our source file directly looks to be very rare 🤔 How about adding some instructions to be more clear?

> And if we do introduce nodejs we'd better use a real i18n framework than my ad-hoc css-based one

I thought about this previously. Frameworks I researched about mostly need DOM manipulations, or based on some VDOM libraries, which just make everything unnecessary complicated. Would you like to recommend some nice and simple solutions?

> Also, the "import" step include steps for both curl and wget because i know there are system containing one but not the other.

Indeed! The idea is not to cover 100% cases, but to cover 99% cases and make people less confused by giving less options. Similarly, the export process does not cover 100% cases, in order to leave people a clear and simple impression.

**Comment by kennytm** [comment]
> I guess the use case that people don't want to open the website but want to open our source file directly looks to be very rare 🤔 How about adding some instructions to be more clear?

what i mean is this PR introduces a "build" step previously not needed, it's not really about having instructions or not 😅.

> I thought about this previously. Frameworks I researched about mostly need DOM manipulations, or based on some VDOM libraries, which just make everything unnecessary complicated. Would you like to recommend some nice and simple solutions?

i18next? but yes looks like that's no good solutions for localizing long documents 🤔

**Comment by kennytm** [comment]
combined the curl and wget instructions in #21 (preview: https://kennytm.github.io/grafana-export/)

**Comment by breezewish** [comment]
The switch of curl and wget is very awesome! Do I need to port it to this PR?

**Comment by kennytm** [comment]
i'll close this as this has really disrupted the workflow, but will try to copy the look without bringing in too much dependencies (esp. the font) 😊. thanks for the design anyway 😄

**Comment by breezewish** [comment]
Cool! Maybe you can just modify this PR directly, i.e. removing the webpack part. (It also adds some polyfills automatically. Not sure whether we should do it manually).

I think another idea is to include the built content in the repo. Considering that for the content script part you have already did that, this might not be a workflow breaker?

**Comment by kennytm** [comment]
(incorporated into #24, thus closing, thanks.)

**Pull request closed without merging**
